// <auto-generated />
namespace PMS_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RoleModel_Updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoleModel_Updated));
        
        string IMigrationMetadata.Id
        {
            get { return "201905100619234_RoleModel_Updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
