// <auto-generated />
namespace PMS_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Db_Change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Db_Change));
        
        string IMigrationMetadata.Id
        {
            get { return "201905141016298_Db_Change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
